/**
  BuilderComponents

  An object that maps component names to their corresponding React components.
  The object is dynamically generated by importing all components in the current directory except for the index.js file.
  @property {React.Component} componentName - A dynamically generated property of the object for each component found in the directory.
  @returns {object} An object that maps component names to their corresponding React components.
*/
const BuilderComponents = {};
const componentFiles = require.context('.', true, /\.jsx?$/);

componentFiles.keys().forEach((fileName) => {
  if (fileName === './index.js') return; // ignore the current file
  // Derived component name from the file name by removing the file extension and directory path
  const componentName = fileName.replace(/^.+\/([^/]+)\.jsx?$/, '$1');
  BuilderComponents[componentName] = componentFiles(fileName).default;
});

export default BuilderComponents;