export const voiceActingRoles = [
  {
    title: 'Urusei Yatsura',
    role: 'Ten',
    link: 'https://www.animenewsnetwork.com/encyclopedia/anime.php?id=25106',
    imageData: {
      src: '/images/voice_roles/ten.png',
      alt: 'Ten from Urusei Yatsura',
    },
  },
  {
    title: 'Re:cycle of the Penguindrum',
    role: 'Purinchu',
    link: 'https://www.animenewsnetwork.com/encyclopedia/anime.php?id=24213',
    imageData: {
      src: '/images/voice_roles/purinchu.png',
      alt: 'Purinchu from Re:cycle of the Penguindrum',
    },
  },
  {
    title: 'Oshi no Ko',
    role: 'Misc Roles',
    link: 'https://www.animenewsnetwork.com/encyclopedia/anime.php?id=25783',
    imageData: {
      src: '/images/voice_roles/oshi_no_ko.jpg',
      alt: 'X from Oshi no Ko',
    },
  },
];

export const mainCredits = [
  {
    link: 'https://twitter.com/tsulala',
    title: 'Rem',
    body: 'Artist',
    image: '/images/credits_art/Rem.jpg',
  },
  {
    link: 'https://twitter.com/Calavera_vt',
    title: 'Calavera',
    body: 'Rigger',
    image: '/images/credits_art/Calavera.jpg',
  },
  {
    link: 'https://twitter.com/JustBiddy_',
    title: 'Vicky',
    body: 'Intro',
    image: '/images/credits_art/Vicky.jpg',
  },
];

export const musicCredits = [
  {
    songName: 'The Way of the Coqui',
    artist: 'InfoDrive',
    track: '',
    songLink: 'https://soundcloud.com/infodrive_vt/the-way-of-the-coqui',
    artistSocials: 'https://www.twitch.tv/infodrive',
    image: '/images/song_art/infoDrive_all.png',
  },
  {
    songName: 'Terrorizer',
    artist: 'InfoDrive',
    track: '',
    songLink: 'https://soundcloud.com/infodrive_vt/terrorizer',
    artistSocials: 'https://www.twitch.tv/infodrive',
    image: '/images/song_art/infoDrive_all.png',
  },
  {
    songName: 'Badass',
    artist: 'InfoDrive',
    track: '',
    songLink: 'https://soundcloud.com/infodrive_vt/badass',
    artistSocials: 'https://www.twitch.tv/infodrive',
    image: '/images/song_art/infoDrive_all.png',
  },
  {
    songName: 'Fall In',
    artist: 'InfoDrive',
    track: '',
    songLink: 'https://soundcloud.com/infodrive_vt/fall-in',
    artistSocials: 'https://www.twitch.tv/infodrive',
    image: '/images/song_art/infoDrive_all.png',
  },
  {
    songName: "Flexin'",
    artist: 'InfoDrive',
    track: '',
    songLink: 'https://soundcloud.com/infodrive_vt/flexin',
    artistSocials: 'https://www.twitch.tv/infodrive',
    image: '/images/song_art/infoDrive_all.png',
  },
  {
    songName: 'Froggy Footwork',
    artist: 'InfoDrive',
    track: '',
    songLink: 'https://soundcloud.com/infodrive_vt/froggy-footwork',
    artistSocials: 'https://www.twitch.tv/infodrive',
    image: '/images/song_art/infoDrive_all.png',
  },
  {
    songName: 'From The Top',
    artist: 'InfoDrive',
    track: '',
    songLink: 'https://soundcloud.com/infodrive_vt/from-the-top',
    artistSocials: 'https://www.twitch.tv/infodrive',
    image: '/images/song_art/infoDrive_all.png',
  },
  {
    songName: 'Bells Of The Frog',
    artist: 'InfoDrive',
    track: '',
    songLink: 'https://soundcloud.com/infodrive_vt/bells-of-the-frog',
    artistSocials: 'https://www.twitch.tv/infodrive',
    image: '/images/song_art/infoDrive_all.png',
  },
  {
    songName: 'Köngäs - Ocho (feat. Coqui)',
    artist: 'Köngäs',
    track: '',
    songLink: 'https://distrokid.com/hyperfollow/kngs3/ocho-feat-coqui-2',
    artistSocials: 'https://hyperfollow.com/kongas',
    image: '/images/song_art/kongas_ocho.jpg',
  },
  {
    songName: 'A Relaxing Army of Frogs',
    artist: 'CrossingsVT',
    track: 'aRelaxingArmyOfFrogs_crossingsVT.mp3',
    songLink: 'https://on.soundcloud.com/tPZnEY8cinvFS87h9',
    artistSocials: 'https://twitter.com/CrossingsVT',
    image: '/images/song_art/generic.jpg',
  },
  {
    songName: 'The Nyaa Song',
    artist: 'Nodens',
    track: 'theNyaaSong_nodens.mp3',
    songLink: '',
    artistSocials: 'https://twitter.com/Nodens64',
    image: '/images/song_art/generic.jpg',
  },
  {
    songName: 'The Licker Store',
    artist: 'HardNormalMatty',
    track: 'lickerStore_hardNormalMatty.mp3',
    songLink: 'https://soundcloud.com/hnmatty/licker-store',
    artistSocials: 'https://hogchildsound.bandcamp.com',
    image: '/images/song_art/matty_lickerStore.jpg',
  },
  {
    songName: 'Delinquent Grace',
    artist: 'corpse_ch',
    track: 'delinquentGrace_corpse.mp3',
    songLink: 'https://www.youtube.com/watch?v=MrrnZsMFxJA',
    artistSocials: 'https://x.com/corpse_ch',
    image: '/images/song_art/corpse_delinquentGrace.jpg',
  },
];

export const miscCredits = [
  {
    link: 'https://twitter.com/king_kriminal',
    title: 'Krimbo',
    body: '1.0 Logo',
    image: '/images/credits_art/Krimbo.jpg',
  },
  {
    link: 'https://twitter.com/AriyaSusanto',
    title: 'ARS',
    body: '1.0 Pops',
    image: '/images/credits_art/ARS.jpg',
  },
  {
    link: 'https://twitter.com/Faulerro',
    title: 'Faulerro',
    body: 'Channel Emotes',
    image: '/images/credits_art/Faulerro.jpg',
  },
  {
    link: 'https://twitter.com/MachachaFulgrim',
    title: 'Macha-cha',
    body: 'Channel Emotes',
    image: '/images/credits_art/Macha-cha.jpg',
  },
  {
    link: 'https://twitter.com/FoxReallyWell',
    title: 'FoxFriend4U',
    body: 'Channel Emotes',
    image: '/images/credits_art/FoxFriend4U.jpg',
  },
  {
    link: 'https://twitter.com/theblortch',
    title: 'TheBlortch',
    body: 'Animations & Emotes',
    image: '/images/credits_art/TheBlortch.jpg',
  },
  {
    link: 'https://twitter.com/MuttleyStrike',
    title: 'MuttleyStrike',
    body: 'Alt Model - Frogsuit',
    image: '/images/credits_art/MuttleyStrike.jpg',
  },
  {
    link: 'https://www.twitch.tv/pumpiino',
    title: 'Pumpiino',
    body: 'Alt Model - Sewer Water',
    image: '/images/credits_art/Pumpiino.jpg',
  },
  {
    link: 'https://twitter.com/Inkcurry',
    title: 'Inkcurry',
    body: 'Alt Model - Frog Puppet',
    image: '/images/credits_art/Inkcurry.jpg',
  },
  {
    link: '',
    title: 'Suzuya_Cry',
    body: 'Animated "Now Loading" Screen',
    image: '/images/credits_art/generic.jpg',
  },
  {
    link: 'https://twitter.com/fenef033',
    title: 'fenef033',
    body: 'BRB Screen',
    image: '/images/credits_art/fenef033.jpg',
  },
  {
    link: 'https://twitter.com/flivine',
    title: 'Fliv',
    body: 'Channel Points Icon',
    image: '/images/credits_art/Fliv.jpg',
  },
  {
    link: 'https://twitter.com/DiamondRoseArt',
    title: 'ADiamondRose',
    body: 'C-Word Pass Icon',
    image: '/images/credits_art/ADiamondRose.jpg',
  },
  {
    link: 'https://twitter.com/NotChaott',
    title: 'NotChaott',
    body: 'Blush Emote',
    image: '/images/credits_art/NotChaott.jpg',
  },
  {
    link: '',
    title: 'Roma',
    body: 'Follow Alert',
    image: '/images/credits_art/generic.jpg',
  },
  {
    link: 'https://twitter.com/drynapp',
    title: 'drynapp',
    body: 'Lobby Winter Art',
    image: '/images/credits_art/drynapp.jpg',
  },
  {
    link: 'https://twitter.com/andouilles',
    title: 'Andouilles',
    body: 'Halloween Cat Chibi',
    image: '/images/credits_art/Andouilles.jpg',
  },
  {
    link: 'https://ko-fi.com/svnnydraw',
    title: 'SynnyDraw',
    body: 'Halloween Witch Loading Screen',
    image: '/images/credits_art/SynnyDraw.jpg',
  },
  {
    link: 'https://skeb.jp/@rion04170419',
    title: 'rion04170419',
    body: 'Twitch Banner',
    image: '/images/credits_art/rion04170419.jpg',
  },
  {
    link: 'https://twitter.com/Shenrix_',
    title: 'Shenrix',
    body: 'Channel Emotes',
    image: '/images/credits_art/Shenrix.jpg',
  },
  {
    link: '',
    title: 'Migu',
    body: 'Channel Emotes',
    image: '/images/credits_art/generic.jpg',
  },
];
